- hosts: all
  roles:
    - nginx
    - geerlingguy.mysql
    - kms
    - openvidu
    - supervisord
    - demos
    - stats

  vars:
    mysql_root_password_update: no
    mysql_root_home: /home/ubuntu
    mysql_root_username: root
    mysql_root_password: egh1erieVi8oph%
    mysql_databases: [
      name: openvidu_sample_app
    ]
