- hosts: all
  roles:
    - role: geerlingguy.mysql
      become: yes

  vars:
    mysql_root_password_update: no
    mysql_root_home: /root
    mysql_root_username: root
    mysql_root_password: egh1erieVi8oph%
    mysql_databases: [
      name: openvidu_sample_app
    ]
EOF