- hosts: kurento
  roles:
    - kms
    - file-server
    
- hosts: openvidu
  roles:
    - geerlingguy.docker
    - nginx
    - coturn
    - openvidu
    - elastic
    - supervisord
    - system-shutdown

