---
- name: installing supervisor
  apt:
    name: supervisor
    update_cache: yes

- name: copying supervisor openvidu stanza
  copy:
    src: "openvidu.conf"
    dest: "/etc/supervisor/conf.d/openvidu.conf"
    mode: "0755"
  notify:
    - restart supervisor

