---
- name: start kibana
  service: 
    name: kibana
    state: started
    enabled: true

- name: stop kibana
  service: 
    name: kibana
    state: stopped

- name: restart kibana
  service: 
    name: kibana
    state: restarted

- name: restart elasticsearch
  service: 
    name: elasticsearch
    state: restarted
    enabled: true