---
- name: preconfiguring coturn
  template:
    src: "coturn.j2"
    dest: "/etc/default/coturn"

- name: preconfiguring turnserver
  template:
    src: "turnserver.conf.j2"
    dest: "/etc/turnserver.conf"
  notify: restart coturn

- name: preconfiguring Kurento Media Server
  template:
    src: "WebRtcEndpoint.conf.ini.j2"
    dest: "/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini"
  notify: restart kms

- name: preconfiguring Kurento Media Server
  template:
    src: "BaseRtpEndpoint.conf.ini.j2"
    dest: "/etc/kurento/modules/kurento/BaseRtpEndpoint.conf.ini"
  notify: restart kms