---
- name: Ensure dependency is installed (Ubuntu).
  apt: 
    name: apt-transport-https
    state: present

- name: Add Elastic apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repository.
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
    state: present
    update_cache: true

- name: Install Elastic's Packages.
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - elasticsearch
    - kibana

- name: adding kibana conf
  copy: 
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
  notify: start kibana

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: started
    enabled: true

