---
- name: copying openvidu launch script
  template:
    src: "openvidu-server.sh"
    dest: "/usr/local/bin"
    mode: "u+rwx,g+rx,o+rx"

- name: copying script for aws signal
  template:
    src: "check_app_ready.sh"
    dest: "/usr/local/bin"
    mode: "0755"
  when: run_ec2

- name: creating recording directory
  file:
    path: /opt/openvidu/recordings
    state: directory
    mode: 0777

- name: creating custom-layout directory
  file:
    path: /opt/openvidu/custom-layout
    state: directory
    mode: 0777