---
- name: Cheking if docker group exists
  group:
    name: docker
    state: present

- name: Removing old docker packages
  apt: 
    name: "{{ item }}"
    state: absent
  with_items:
    - docker 
    - docker-engine

- name: Install necessary software
  apt:  
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates 
    - curl
    - software-properties-common

- name: Adding Docker PGP key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

- name: Adding Docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

- name: Installing docker
  apt:
    name: docker-ce
    state: present


