---
- name: adding kurento PGP key
  apt_key: 
    url: "http://ubuntu.kurento.org/kurento.gpg.key"
    state: present

- name: adding kurento repository
  apt_repository:
    repo: "deb http://ubuntu.kurento.org xenial kms6"

- name: installing necesary software
  apt:
    name: coturn

- name: preconfiguring coturn
  template:
    src: "coturn.j2"
    dest: "/etc/default/coturn"

- name: preconfiguring turnserver
  template:
    src: "turnserver.conf.j2"
    dest: "/etc/turnserver.conf"
  notify: restart coturn

- name: installing Kurento Media Server
  apt:
    name: "kurento-media-server-6.0"
    update_cache: yes
  notify: start kms

- name: preconfiguring Kurento Media Server
  template:
    src: "WebRtcEndpoint.conf.ini.j2"
    dest: "/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini"
  notify: restart kms
