---
- name: installing necesary software
  apt:
    name: coturn

- name: preconfiguring coturn
  template:
    src: "coturn.j2"
    dest: "/etc/default/coturn"

- name: preconfiguring turnserver
  template:
    src: "turnserver.conf.j2"
    dest: "/etc/turnserver.conf"
  notify: restart coturn

