---
- name: installing mysql
  apt: name=mysql-server state=installed

- name: installing python mysqldb module
  apt: name=python-mysqldb state=latest 

- name: setting root password
  mysql_user: 
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    priv: "*.*:ALL,GRANT"
    state: "present"
  with_items:
    - "%"
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Add .my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: forcing to use tcp instead of socket for root@localhost
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_pass }}'
  changed_when: False

- name: creating database
  mysql_db: 
    name: "{{ mysql_database }}"
    state: "present"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"


